[profile.default]

libs = ["node_modules", "lib"]
test = "tests"
remappings = [
  '@forge-std/=lib/forge-std/src/',
  '@openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
]
solc = "0.8.19"

[fmt]
quote_style = 'single'
int_types = 'short'

# See more config options https://github.com/gakonst/foundry/tree/master/config
